// Created by iWeb 3.0.4 local-build-20160425

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,587),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_1.png'},{rect:new IWRect(1,-1,406,2),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_2.png'},{rect:new IWRect(407,-1,2,2),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_3.png'},{rect:new IWRect(407,1,2,587),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_4.png'},{rect:new IWRect(407,588,2,3),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_5.png'},{rect:new IWRect(1,588,406,3),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_6.png'},{rect:new IWRect(-1,588,2,3),url:'Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/stroke_7.png'}],new IWSize(408,590))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Underground_Pipe_and_Propane_Tank_Cathodic_Protection_files/Underground_Pipe_and_Propane_Tank_Cathodic_ProtectionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');detectBrowser();adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
